name: notes_app
description: A clean architecture Flutter Notes App with Firebase, GetX, and GoRouter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  get: ^4.6.6

  # Navigation
  go_router: ^13.2.0

  # Firebase
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9

  # UI
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  iconsax: ^0.0.8

  # Utils
  uuid: ^4.3.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
