// THIS FILE IS GENERATED BY FLUTTERFIRE CLI
// Run: flutterfire configure
// Do NOT edit manually.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ⚠️ REPLACE THESE VALUES with your own Firebase project config

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQnaNtgQkBMgj1yJCl1ZtQN1knfTw16Eg',
    appId: '1:155966384697:web:344d90291edd777154fbe8',
    messagingSenderId: '155966384697',
    projectId: 'note-f3247',
    authDomain: 'note-f3247.firebaseapp.com',
    storageBucket: 'note-f3247.firebasestorage.app',
    measurementId: 'G-NLCLFHPJQ1',
  );

  // Run: flutterfire configure

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBorIuYFtVDi5NjItqy7XWuZ0KrrovOhIo',
    appId: '1:155966384697:android:ef0c2958f2c01a9f54fbe8',
    messagingSenderId: '155966384697',
    projectId: 'note-f3247',
    storageBucket: 'note-f3247.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvhbH-qy8wgv_FMRWwzu0-u0GHmHerVk8',
    appId: '1:155966384697:ios:8ceffe88a67de23b54fbe8',
    messagingSenderId: '155966384697',
    projectId: 'note-f3247',
    storageBucket: 'note-f3247.firebasestorage.app',
    iosBundleId: 'com.ebrahim.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvhbH-qy8wgv_FMRWwzu0-u0GHmHerVk8',
    appId: '1:155966384697:ios:8ceffe88a67de23b54fbe8',
    messagingSenderId: '155966384697',
    projectId: 'note-f3247',
    storageBucket: 'note-f3247.firebasestorage.app',
    iosBundleId: 'com.ebrahim.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQnaNtgQkBMgj1yJCl1ZtQN1knfTw16Eg',
    appId: '1:155966384697:web:26d1073e9e3f3c3254fbe8',
    messagingSenderId: '155966384697',
    projectId: 'note-f3247',
    authDomain: 'note-f3247.firebaseapp.com',
    storageBucket: 'note-f3247.firebasestorage.app',
    measurementId: 'G-GBQ50RPLWR',
  );

}